[package]
name = "gm_execute"
version = "2.0.0"
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
mlua = { path = "vendor/mlua", features = ["luajit", "vendored", "module"] }
which = "4.2"
anyhow = "1.0"
thiserror = "1.0"
